[package]
name = "uair"
version = "0.6.2"
authors = ["Rishabh Das <rdas@tutanota.com>"]
edition = "2021"
description = "An extensible pomodoro timer"
license = "MIT"
repository = "https://github.com/metent/uair/"
keywords = ["pomodoro", "timer", "countdown", "cli", "productivity"]
categories = ["command-line-utilities"]

[dependencies]
argh = "0.1.12"
async-io = "2.4.0"
async-net = "2.0.0"
bincode = "1.3.3"
futures-lite = "2.5.0"
humantime = "2.1.0"
humantime-serde = "1.1.1"
log = "0.4.22"
serde = { version = "1.0.214", features = ["derive"] }
serde_ignored = "0.1.10"
signal-hook = "0.3.17"
signal-hook-async-std = "0.2.2"
simplelog = "0.12.2"
thiserror = "2.0.3"
toml = "0.8.19"
winnow = "0.6.20"

[dev-dependencies]
testing_logger = "0.1"
