name: CI

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install latest stable Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check
        run: cargo check --locked
      - name: Lint
        run: cargo clippy --all-targets -- -D warnings
      - name: Format
        run: cargo fmt --check
      - name: Test
        run: cargo test
